# Generated by Django 5.2.2 on 2025-06-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BLog',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('blog_text',
                 models.TextField(
                     max_length=1000)),
                ('pub_date',
                 models.DateTimeField(
                     verbose_name='date published')),
            ],
        ),
    ]
