# Generated by Django 5.2.2 on 2025-06-16 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.UUID('e9b31f4c-2c18-46ec-a676-37d1878c3aa4'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.UUID('2ce0b98b-d958-4290-aac8-e00cab9624c6'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('payment_methods_id', models.UUIDField(default=uuid.UUID('c11b70c0-5fbb-43d7-9260-599e51bf2d46'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.UUIDField(default=uuid.UUID('432f54aa-4700-4656-a294-dc530bc95d30'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(default=uuid.UUID('991eacfa-1d2d-4a5a-9e8b-cc41e4f8f4ac'), editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=400)),
                ('address_type', models.CharField(max_length=100)),
                ('pincode', models.PositiveIntegerField(max_length=6)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.UUID('9f70e0c5-2e33-4613-9a75-9c556e36094f'), editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.UUID('f1bca3c7-2ba8-41f9-98c1-7932fdc926b9'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('details', models.TextField(max_length=500)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.category')),
                ('Vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.UUIDField(default=uuid.UUID('5259134f-35df-4bdc-8990-783f9464d116'), editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.product'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('product_image_id', models.UUIDField(default=uuid.UUID('459d4e3d-4ce6-43b9-b0a3-7f7676e09241'), editable=False, primary_key=True, serialize=False)),
                ('product_images', models.URLField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.UUID('cb7b7e3a-edc8-4204-b1a2-09c11ba91aab'), editable=False, primary_key=True, serialize=False)),
                ('review_detail', models.TextField(max_length=500)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('review_images_id', models.UUIDField(default=uuid.UUID('da5bcea2-12d4-431b-915c-6eb60c07ad6b'), editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.review')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.product')),
            ],
        ),
    ]
