# Generated by Django 5.2.2 on 2025-06-16 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.UUIDField(default=uuid.UUID('d9692509-ee44-4a89-92ff-4dd380507ec3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('79e495e8-b83d-4e84-a876-fb3465d4578f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('fc1a3eff-a764-457d-88c0-085b26a2b5a2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('25a1ade6-9075-4b87-a8ea-ab5c92f67a2c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_id',
            field=models.UUIDField(default=uuid.UUID('b5f37569-2335-4a8e-8944-a2c21df98f5a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_methods_id',
            field=models.UUIDField(default=uuid.UUID('236dc3f2-1a00-408a-95b3-8e6b89ecd1c4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('c711918a-c386-4902-be42-96018d5e540c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product_image_id',
            field=models.UUIDField(default=uuid.UUID('06330b73-32d1-43ca-a758-35ea5850614f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.UUIDField(default=uuid.UUID('e99d5acc-05f4-42de-87eb-0c80c0a17c63'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewimages',
            name='review_images_id',
            field=models.UUIDField(default=uuid.UUID('883b87eb-d958-4569-b9f4-af7ac216909d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('fe7f0b84-d3b6-499f-95f4-2360fa8a4a16'), editable=False, primary_key=True, serialize=False),
        ),
    ]
