# Generated by Django 5.2.2 on 2025-06-16 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website',
         '0002_alter_address_address_id_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.UUIDField(default=uuid.UUID('774476a6-5de1-427d-a9d3-c9396bfd9e45'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('b2277e5a-49d6-42fe-8e6f-2f3d9874d407'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('a77768cd-fa99-457e-8d04-b8b7c66a9fa9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('ea427f60-d4b0-4fd5-addc-4111791dddf0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_id',
            field=models.UUIDField(default=uuid.UUID('1e4464ab-efe2-4d8d-b387-e7eacee90981'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='payment_methods_id',
            field=models.UUIDField(default=uuid.UUID('a81f2eba-4844-424f-a294-aaf66dbc55e3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('57c53be6-51ae-4144-906f-f0f04c3e435a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product_image_id',
            field=models.UUIDField(default=uuid.UUID('6f19799c-9b0a-426a-8047-f29ba66ae605'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.UUIDField(default=uuid.UUID('a321dcc1-463a-47fe-97a1-47b40630c50c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewimages',
            name='review_images_id',
            field=models.UUIDField(default=uuid.UUID('b561b075-ac7f-4cfd-883d-766faf309115'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('b51f0f07-a99d-4be5-9a9d-97e9e7c6d903'), editable=False, primary_key=True, serialize=False),
        ),
    ]
