# Generated by Django 5.2.2 on 2025-06-17 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website',
         '0003_alter_address_address_id_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_methods_id', models.UUIDField(default=uuid.UUID('26e703b0-0605-4b18-9050-f1dfe892cf6c'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_image_id', models.UUIDField(default=uuid.UUID('004e2e55-e4ab-4eb7-86cd-86f9c5467da5'), editable=False, primary_key=True, serialize=False)),
                ('product_images', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('review_images_id', models.UUIDField(default=uuid.UUID('84a538df-863a-4da5-ae38-50258a593453'), editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentMethods',
        ),
        migrations.RemoveField(
            model_name='reviewimages',
            name='review_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='default123', max_length=54),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.UUIDField(default=uuid.UUID('f5ea9360-59d3-44e7-b065-16143c041e8f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('519344d1-3f3f-4520-b524-0160a98b7364'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('43ac12dd-23de-44d4-b80a-7213accd5500'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('2266bd45-d863-4b10-9b1c-c266b7de3411'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_id',
            field=models.UUIDField(default=uuid.UUID('d251ee2c-860b-4d2e-8167-0e9409de0c26'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('dfff43de-3253-4178-ae7f-a20611789841'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.UUIDField(default=uuid.UUID('322575ba-3da5-4484-9ecd-9135e5bd8290'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('ad0e05f5-f70e-4429-8f80-1c717c306ac0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.product'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_website.review'),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
        migrations.DeleteModel(
            name='ReviewImages',
        ),
    ]
