# Generated by Django 5.2.2 on 2025-06-17 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website',
         '0004_paymentmethod_productimage_reviewimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.UUIDField(default=uuid.UUID('32eafc53-2abe-435f-8c3c-19a9ad03e12d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('c574ae62-cfa9-41d3-9a85-bc6ac280d88f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('602efbdc-e6f9-40c8-a615-dec2598d3fc8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('3f5a78b1-ab22-45c9-81bd-ebca5a41dac7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_id',
            field=models.UUIDField(default=uuid.UUID('0ce09010-f856-41c9-af50-6f06754b46f3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_methods_id',
            field=models.UUIDField(default=uuid.UUID('25bb15cb-1bfc-4a9a-92d0-229a6c288f2a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('6d509723-be62-4b56-9ccc-a2d62bae3ef8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image_id',
            field=models.UUIDField(default=uuid.UUID('b7897dcc-67c5-4eb7-803a-13eee8c8a21b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.UUIDField(default=uuid.UUID('f848a237-c07a-482b-b49b-cad75f1abb2b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='review_images_id',
            field=models.UUIDField(default=uuid.UUID('cc51687c-cdd8-4eb4-9a18-bc933fe13203'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('940dab7d-9baf-4a8a-89ea-b0e4ad2e8f24'), editable=False, primary_key=True, serialize=False),
        ),
    ]
