# Generated by Django 5.2.2 on 2025-06-17 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0005_customer_is_verified_alter_address_address_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_id',
            field=models.UUIDField(default=uuid.UUID('cf0fbd41-8d58-4950-92e2-4836ad3d1b57'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.UUIDField(default=uuid.UUID('2fedb429-a554-46c0-a5dc-a1930b9167a9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.UUIDField(default=uuid.UUID('0f158f90-d767-412f-8e0e-c609d1637e91'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('2e39a7f8-ab20-463e-a6ce-457e046031c9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_id',
            field=models.UUIDField(default=uuid.UUID('7a1b0702-20c3-4c50-9890-7875d5953ede'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_methods_id',
            field=models.UUIDField(default=uuid.UUID('f2c9f941-dddd-44fd-aca9-b16d8a949aa6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.UUIDField(default=uuid.UUID('c4fdef1e-a63b-4f07-98fc-28d7ab0eb94a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image_id',
            field=models.UUIDField(default=uuid.UUID('087b873a-f2e4-4fe7-a6ec-5114dc9adb85'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.UUIDField(default=uuid.UUID('01962abc-7fe1-4890-b29b-63287a100209'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='review_images_id',
            field=models.UUIDField(default=uuid.UUID('584f9b78-0b87-4395-832b-0e6645b5fbc2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.UUIDField(default=uuid.UUID('57d4f897-288f-4901-a699-9f23c4178b3c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
