# Generated by Django 5.2.2 on 2025-06-19 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='DOB',
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.date(2025, 6, 19)),
        ),
    ]
